cw__17/Models/Contract/CategoryContract/ICategoryRepository.cs
using cw__17.Models.Entities;

namespace cw__17.Models.Contract.CategoryContract
{
    public interface ICategoryRepository
    {
        public void Creat(Category category);
        public List<Category> GetAll();
    }
}

cw__17/Models/Contract/CategoryContract/ICategoryService.cs
using cw__17.Models.Entities;

namespace cw__17.Models.Contract.CategoryContract
{
    public interface ICategoryService
    {
        public void Creat(Category category);
        public List<Category> GetAll();
    }
}

cw__17/Models/Contract/ProductContract/IProductRepository.cs
using cw__17.Models.Entities;
namespace cw__17.Models.Contract.ProductContract
{
    public interface IProductRepository
    {
       public List<Product> GetAll();
        public void AddProduct(Product product);
        
    }
}

cw__17/Models/Contract/ProductContract/IProductService.cs
using cw__17.Models.Entities;

namespace cw__17.Models.Contract.ProductContract
{
    public interface IProductService
    {
        public List<Product> GetAll();
        public void CreatProduct(Product product);
    }
}

cw__17/Models/Contract/UserContract/IUserRepository.cs
using cw__17.Models.Entities;

namespace cw__17.Models.Contract.UserContract
{
    public interface IUserRepository
    {
        public void Add(User user);
        public void Delete(int id);
        public User Get(int id);
        public void Update(int id);
        public List<User> GetAll();
        public User GetByUserName(string userName);
    }
}

cw__17/Models/Contract/UserContract/IUserService.cs
using cw__17.Models.Entities;

namespace cw__17.Models.Contract.UserContract
{
    public interface IUserService
    {
        public void AddUser(User user);
        public void DeleteUser(int id);
        public User GetUser(int id);
        public void Update(int id);
        public bool Login(string userName,string password);
        public bool Register (string firstName,string lastName,string userName,string Password);
        public List<User> GetUsers();
    }
}

cw__17/Models/Entities/Category.cs
namespace cw__17.Models.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<Product>? Products { get; set; } = new List<Product>();
    }
}

cw__17/Models/Entities/Product.cs
namespace cw__17.Models.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Count { get; set; }
        public Category Category { get; set; }
        public int CategoryId { get; set; }
    }
}

cw__17/Models/Entities/User.cs
namespace cw__17.Models.Entities
{
    public class User
    {
        public int Id { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; } = false;
        public decimal Balance { get; set; } = 1000000;
        public List<Product> Products { get; set; }
    }
}

cw__17/Models/ErrorViewModel.cs
namespace cw__17.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

cw__17/Controllers/AutenticationController.cs
using cw__17.AppDataBase;
using cw__17.Models.Contract.UserContract;
using cw__17.Service;
using Microsoft.AspNetCore.Mvc;

namespace cw__17.Controllers
{
    public class AutenticationController : Controller
    {
        IUserService _userService = new UserService();
      
       public IActionResult login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string username,string password)
        {
            if(_userService.Login(username, password) == false)
            {
                TempData["Message"] = "Username or Password is NotValid ";
                TempData["AlertType"] = "danger";
                return View();

            }
            
            TempData["Message"] = "You are Login";
            TempData["AlertType"] = "Success";
            return View();

        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(string firstname,string lastname,string username,string password)
        {
           
            if (_userService.Register(firstname, lastname, username, password) == false)
            {

                TempData["Message"] = "Username is Exist";
                TempData["AlertType"] = "danger";
                return View();
            }
            TempData["Message"] = "You are Register";
            TempData["AlertType"] = "Success";
            
            return View();
        }
        public IActionResult LogOut()
        {
            CurrentUser.CurentUser = null;
            return Redirect("/Autentication/Login");
        }

        
    }
}

cw__17/Controllers/CategoryController.cs
using cw__17.AppDataBase;
using cw__17.Models.Contract.CategoryContract;
using cw__17.Models.Entities;
using cw__17.Service;
using Microsoft.AspNetCore.Mvc;

namespace cw__17.Controllers
{
    public class CategoryController : Controller
    {
        ICategoryService categoryService = new CategoryService();
        public IActionResult Index()
        {
            if(CurrentUser.CurentUser == null)
            {
                return Redirect("/Autentication/Login");
            }
            var cats = categoryService.GetAll();

            return View(cats);
        }
        [HttpPost]
        public IActionResult Add(string Title)
        {
            Category category = new Category() {Title =  Title};
            categoryService.Creat(category);
            return RedirectToAction("Index");

        } 
    }
}

cw__17/Controllers/HomeController.cs
using System.Diagnostics;
using cw__17.Models;
using Microsoft.AspNetCore.Mvc;

namespace cw__17.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

cw__17/Controllers/ProductController.cs
using cw__17.AppDataBase;
using cw__17.Models.Contract.ProductContract;
using cw__17.Models.Entities;
using cw__17.Service;
using Microsoft.AspNetCore.Mvc;

namespace cw__17.Controllers
{
    public class ProductController : Controller
    {


        IProductService _productService = new ProductService();
        public IActionResult Index()
        {
            if (CurrentUser.CurentUser == null)
            {
                return Redirect("/Autentication/Login");
            }
            var pro = _productService.GetAll();

            return View(pro);
        }
        public IActionResult Add(Product product)
        {
            var pro = new Product()
            {
                Name = product.Name,
                Price = product.Price,
                Category = product.Category,
                Count = product.Count
            };
           _productService.CreatProduct(pro);
            return RedirectToAction("Index");
        }
        
    }
}

cw__17/Views/Autentication/Register.cshtml
@{
	ViewData["Title"] = "Register";
}
@if (TempData["Message"] != null)
{
	<div class="alert alert-@TempData["AlertType"] alert-dismissible fade show" role="alert">
		@TempData["Message"]
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
}

<div class="container">
	<h2 class="text-center mb-4">Register</h2>
	<form method="post" action="Register">
		<div class="mb-3">

			<label for="firstname" class="form-label">Firstname</label>
			<input type="text" class="form-control" id="firstname" name="firstname" placeholder="Enter your firstname" required>
		</div><div class="mb-3">

			<label for="lastname" class="form-label">Lastname</label>
			<input type="text" class="form-control" id="lastname" name="lastname" placeholder="Enter your lastname" required>
		</div>
		<div class="mb-3">

			<label for="username" class="form-label">Username</label>
			<input type="text" class="form-control" id="username" name="username" placeholder="Enter your username" required>
		</div>

		<div class="mb-3">
			<label for="password" class="form-label">Password</label>
			<input type="password" class="form-control" id="password" name="password" placeholder="Enter your password" required>
		</div>
		<button type="submit" class="btn btn-primary w-100">Register</button>
	</form>
</div>

cw__17/Views/Autentication/login.cshtml
@{
	ViewData["Title"] = "Login";
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-@TempData["AlertType"] alert-dismissible fade show" role="alert">
        @TempData["Message"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Login Page</title>
    <style>
        body {
            background-color: #f8f9fa;
        }

        .login-container {
            margin-top: 100px;
        }

        .login-form {
            padding: 20px;
            border-radius: 5px;
            background-color: white;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>
<body>
   
    <div class="container login-container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <form class="login-form" method="post" asp-action="Login">
                    <h2 class="text-center">Login</h2>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control" id="username" placeholder="Enter username" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Enter password" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                    <div class="text-center mt-3">
                        <a href="#">Forgot Password?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

cw__17/Views/Category/Index.cshtml
@using cw__17.Models.Entities;
@model List<Category>
<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">
	Add Category
</button>

<div class="modal" tabindex="-1" id="modal">
	<div class="modal-dialog" >
		<div class="modal-content">
			<form asp-action="Add">
				<div class="modal-body">


					<label id="Title" name="Title">
						Title
					</label>
					<input type="text" id="Title" name="Title" />

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save</button>

				</div>
			</form>
		</div>
	</div>
</div>

<table class="table table-bordered table-responsive table-primary table-hover">
	<thead>
		<tr>
			<th>شناسه</th>
			<th>عنوان دسته بندی </th>

		</tr>
	</thead>
	<tbody>
		@foreach (var item in @Model)
		{
			<tr>
				<td>@item.Id</td>
				<td>@item.Title</td>

			</tr>
		}
	</tbody>
</table>

cw__17/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4">Welcome</h1>
	<p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

cw__17/Views/Product/Index.cshtml
@using cw__17.Models.Entities;
@model List<Product>
<div class="modal" tabindex="-1" id="modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form asp-action="Add">
				<div class="modal-body">


						<label id="Id" name="Id">
					<label id="Name" name="Name">
							<label id="Price" name="Price">
								<label id="Count" name="Count">
						Title
					</label>
					<input type="text" id="Id" name="Id" />
								<input type="text" id="Name" name="Name" />
								<input type="text" id="Price" name="Price" />
								<input type="text" id="Count" name="Count" />

				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save</button>

				</div>
			</form>
		</div>
	</div>
</div>
<table class="table table-bordered table-responsive table-primary table-hover">
	<thead>
		<tr>
			<th>شناسه</th>
			<th>عنوان کالا</th>
			<th>قیمت</th>
			<th>تعداد موجودی</th>
			
		</tr>
	</thead>
	<tbody>
		@foreach (var item in @Model)
		{
			<tr>
				<td>@item.Id</td>
				<td>@item.Name</td>
				<td>@item.Price</td>
				<td>@item.Count</td>
				
			</tr>
		}
	</tbody>
</table>

cw__17/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cw__17</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cw__17.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cw__17</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categorys</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autentication" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autentication" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="LogOut" asp-controller="Autentication" class="btn btn-danger">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - cw__17 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

cw__17/Views/User/Index.cshtml
@using cw__17.Models.Entities
@model List<User>
<table class="table table-bordered table-responsive table-primary table-hover">
	<thead>
		<tr>
			<th>شناسه</th>
			<th>نام</th>
			<th>نام خانوادگی</th>
			<th> موجودی</th>
			<th> نام کاربری</th>
			<th> رمز عبور</th>

		</tr>
	</thead>
	<tbody>
		@foreach (var user in @Model)
		{
			<tr>
				<td>@user.Id</td>
				<td>@user.FirstName</td>
				<td>@user.LastName</td>
				<td>@user.Balance</td>
				<td>@user.UserName</td>
				<td>@user.Password</td>

			</tr>
		}
	</tbody>
</table>